sudo: required
services:
  - docker

before_script:
  - docker pull wiseteam/wykoplaner-backend || true # true to not fail if repository is empty
  - git submodule update --init --remote

script:
  - docker build --pull --cache-from wiseteam/wykoplaner-backend . -f ./Dockerfile.production -t wiseteam/wykoplaner-backend

after_script:
  - docker images

before_deploy:
  - docker login -u "$HUB_USERNAME" -p "$HUB_PASSWORD"

deploy:
  provider: script
  script: docker push wiseteam/wykoplaner-backend
  on:
    branch: master